### ISSUE TITLE
Weineng's todo

### ISSUE THREAD

**Issue by wn** [wn/Pace#24]
TODO:
- [x] Record routes
- [x] Only allow location which has an accuracy of < 10m to be committed to log
- [ ] Allowing locking of map
- [ ] Layout the details nicely
- [x] Create summary page
- [ ] Save routes to firebase
- [ ] Save routes image to firebase

Low priority TODO:
- [ ] Create flags to indicate start and end of routes
